apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: oracle
  name: oracle
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: oracle
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/db23c-default: "true"
        io.kompose.service: oracle
    spec:
      containers:
        - env:
            - name: APP_USER
              value: app
            - name: APP_USER_PASSWORD
              value: Imust-change2023It
            - name: ORACLE_RANDOM_PASSWORD
              value: "true"
          image: gvenzl/oracle-free:latest-faststart
          name: oracle
          ports:
            - containerPort: 1521
          resources: {}
      restartPolicy: Always
status: {}
